# Generated by Django 3.1.7 on 2021-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Update',
            fields=[
                ('newspaper', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mainhead', models.CharField(max_length=1000)),
                ('sports', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=1000)),
                ('business', models.CharField(max_length=1000)),
            ],
        ),
    ]
