# Generated by Django 3.1.7 on 2021-05-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_update',
            name='mainhead',
        ),
        migrations.AddField(
            model_name='news_update',
            name='films',
            field=models.CharField(default='no news', max_length=1000),
        ),
        migrations.AddField(
            model_name='news_update',
            name='politics',
            field=models.CharField(default='no news', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news_update',
            name='business',
            field=models.CharField(default='no news', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news_update',
            name='education',
            field=models.CharField(default='no news', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news_update',
            name='sports',
            field=models.CharField(default='no news', max_length=1000),
        ),
    ]
