# Generated by Django 3.1.7 on 2021-05-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_prefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefer',
            name='id',
        ),
        migrations.AlterField(
            model_name='prefer',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
