# Generated by Django 3.1.7 on 2021-05-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210522_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prefer',
        ),
    ]
