# Generated by Django 3.1.7 on 2021-05-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_prefer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prefer',
        ),
    ]
