# Generated by Django 3.1.7 on 2021-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_prefer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('sports', models.CharField(default='not', max_length=20)),
                ('politics', models.CharField(default='not', max_length=20)),
                ('education', models.CharField(default='not', max_length=20)),
                ('business', models.CharField(default='not', max_length=20)),
                ('films', models.CharField(default='not', max_length=20)),
            ],
        ),
    ]
