# Generated by Django 3.1.7 on 2021-05-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210529_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefer',
            name='msg_type',
            field=models.CharField(default='mail', max_length=20),
        ),
    ]
