# Generated by Django 3.1.7 on 2021-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_prefer_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefer',
            name='sent',
            field=models.CharField(default='nsent', max_length=20),
        ),
    ]
