# Generated by Django 3.1.7 on 2021-05-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_prefer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_update',
            old_name='education',
            new_name='entertainment',
        ),
        migrations.RenameField(
            model_name='news_update',
            old_name='films',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='prefer',
            old_name='education',
            new_name='entertainment',
        ),
        migrations.RenameField(
            model_name='prefer',
            old_name='films',
            new_name='technology',
        ),
        migrations.RemoveField(
            model_name='news_update',
            name='politics',
        ),
        migrations.RemoveField(
            model_name='prefer',
            name='politics',
        ),
    ]
