# Generated by Django 3.1.7 on 2021-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210529_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefer',
            name='business',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='prefer',
            name='entertainment',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='prefer',
            name='sports',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='prefer',
            name='technology',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
